language: python
python:
  - "2.7"
  - pypy
env:
  - REQUESTS=1.2.3
  - REQUESTS=1.1.0
  - REQUESTS=1.0.3
install:
  - "pip install requests==$REQUESTS"
  - "pip install -r requirements.txt"
  - "pip install ."
script:
  - py.test
